name: Add label to the Issue/PR

on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]

env:
  LABEL: test_label

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
        
  labeler:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:

      - name: Create a label on a Issue
        if: ${{ github.event_name == 'issues' }}
        run: | 
          URL="https://api.github.com/repos/$REPO/issues/$ISSUE_NUMBER/labels"
          curl --request POST \
          --header 'authorization: Bearer ${{ env.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --url $URL \
          --data '{"labels":["${{ env.LABEL }}"]}' \
          --fail
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPO: ${{ github.repository }}

      - name: Create a label on the PR
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          URL="https://api.github.com/repos/$REPO/issues/$PR_NUMBER/labels"
          curl --request POST \
          --header 'authorization: Bearer ${{ env.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --url $URL \
          --data '{"labels":["${{ env.LABEL }}"]}' \
          --fail
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
