name: Add label to the Issue/PR

on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]

permissions: read-all

env:
  LABEL: test_label

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:

      - name: Get associated projects
        uses: eduardomp/get-projects-by-issue-action@main
        with:
          issue_number: ${{ github.event.issue.number }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a label on a Issue
        if: ${{ github.event_name == 'issues' }}
        run: | 
          URL="https://api.github.com/repos/$REPO/issues/$ISSUE_NUMBER/labels"
          curl --request POST \
          --header 'authorization: Bearer ${{ env.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --url $URL \
          --data '{"labels":["${{ env.LABEL }}"]}' \
          --fail
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_HTML_URL: ${{ github.event.issue.html_url }}
          ORG: ${{ github.event.organization.login }}
          REPO: ${{ github.repository }}

      - name: Create a label on the PR
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          URL="https://api.github.com/repos/$REPO/issues/$PR_NUMBER/labels"
          curl --request POST \
          --header 'authorization: Bearer ${{ env.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --url $URL \
          --data '{"labels":["${{ env.LABEL }}"]}' \
          --fail
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
